/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms
 By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed n, find the sum of the even-valued terms.
*/

function fiboEvenSum(n) {
	let sum = 2;
	let f1 = 1;
	let f2 = 2;
	while (f1 + f2 <= n) {
		let f = f1 + f2;
		console.log(f);
		if ( f % 2 == 0) {
			sum += f;
		}
		f1 = f2;
		f2 = f;
	}
	return sum;
}

console.log(fiboEvenSum(34));